#################################################
#                                               #
#            CONFIGURAÇÃO DO SISTEMA            #
#                                               #
#################################################

#Configuração do MySQL
MySQL:
  Usar: false
  IP: 'localhost'
  Porta: '3306'
  Database: ''
  Usuario: ''
  Senha: ''

#Caso queira usar UUIDs como forma de armazenamento no MySQL, ative
#Flatfile SEMPRE usará UUIDs como forma de armazenamento
Usar-UUIDs: true

#################################################
#                                               #
#            CUSTOMIZAÇÃO DO SISTEMA            #
#                                               #
#################################################

#Aviso:
#Todas as mensagens são configuradas no arquivo mensagens.yml

#Se deseja que o plugin envie uma mensagem privada ao jogador quando upar, ative isso
Enviar-Mensagem: true

#Se deseja que o plugin envie um broadcast quando o jogador upar, ative isso
Anuncio: true

#Se deseja que o plugin envie um broadcast diferenciado quando o jogador upar ao rank maximo, ative isso
Anuncio-Rank-Maximo: true

#Se deseja que o plugin solte um foguete quando o jogador upar, ative isso
Soltar-Foguete: true

#Configuração do GUI para upar de rank
Rankup-GUI:
  Usar: true
  Nome: "&d&lMenu de &a&lRANKUP"
  
  #Configuração dos itens 
  Item_UP:
    ID: "35:5"
    Nome: "&a&lConfirmar UP!"
    Lore:
    - ''
    - '&e&lClique aqui para confirmar o &a&lRANKUP'
    - '&7Você ficará com: &c@restante'
    - ''
  Item_Cancelar:
    ID: "35:14"
    Nome: "&c&lCancelar UP!"
    Lore:
    - ''
    - '&e&lClique aqui para cancelar o UP!'
    - ''
  Item_Rank:
    Cabeca:
      #Deseja que o item do rank seja uma cabeça? Se sim, coloque true no campo abaixo.
      Modo-Cabeca: false
      
      #Caso queira usar a cabeça de um certo jogador, coloque o nome dele aqui
      #Você também pode usar a cabeça do jogador que executou o comando
      #Nesse caso, coloque "Jogador" no campo abaixo.
      Cabeca: Jogador
    #Caso esteja no modo cabeça, você pode deixar este campo em branco
    ID: "421"
    Nome: "&e&lUpar para o rank: @rank"
    Lore:
    - ''
    - '&e&lPróximo rank: @rank'
    - '&e&lPreço para upar: &a@preco'
    - '&e&lRank atual: @atual'
    - ''
   
#Se deseja enviar titles quando o jogador upar, ative isso e modifique as opções
Title:
  Usar: true
  
  #O modo é a forma como os titles serão enviados.
  #Existem dois modos: Apenas para o jogador que upou (Modo 1) e Todos os jogadores do servidor (Modo 2)
  Modo: 1
  
  #Titulo e Subtitulo são as mensagens que serão exibidas no titles
  #Titulo é o texto de cima; O maior. Subtitulo é o texto de baixo, o menor;
  #Placeholders: 
  #@player = Nome do jogador que upou, @rank = Rank que o jogador upou, @oldrank = Rank que o jogador estava antes de upar
  #@preco = O dinheiro gasto para subir para o rank, @dinheiro = O dinheiro que sobrou após o jogador upar
  Titulo: '&eVocê subiu de rank!'
  Subtitulo: 'Você está agora no rank @rank&r!'
 
#Configuração dos ranks
Ranks:
  Noob:
    Nome: '&f&lNoob&r'
    Tag: '&7[&f&lNoob&7]'
    Preco: 0
    Comandos:
    - 'pex user @player group add noob'
  Mediano:
    Nome: '&a&lMediano&r'
    Tag: '&7[&a&lMediano&7]'
    Preco: 500
    Comandos:
    - 'pex user @player group remove noob'
    - 'pex user @player group add mediano'
    - 'give @player diamond 5'
  Mito:
    Nome: '&b&lMito&r'
    Tag: '&7[&b&lMito&7]'
    Preco: 2500
    Comandos:
    - 'pex user @player group remove mediano'
    - 'pex user @player group add mito'
    - 'give @player diamond 10'